import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { ThemeProvider } from '@/components/theme-provider';
import Nav from '@/components/nav';
import Search from '@/components/search';
import WhatsHappeningPanel from '@/components/what-happening-panel';
import FollowPanel from '@/components/follow-panel';
import Footer from '@/components/footer';

const fontSans = Inter({
	subsets: ['latin'],
	variable: '--font-sans',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' className='dark'>
			<body
				className={cn(
					'min-h-screen bg-background text-foreground font-sans antialiased',
					fontSans.variable
				)}>
				<ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem
					disableTransitionOnChange>
					<div className='min-h-screen flex max-w-7xl mx-auto lg:grid lg:grid-cols-10 gap-5'>
						<Nav />
						<main className='mr-0 lg:mr-5 xl:mr-0 col-span-8 xl:col-span-5 w-full border border-x-input'>
							{children}
						</main>
						<aside className='col-span-3 hidden xl:flex flex-col w-[350px]'>
							<div className='sticky top-0'>
								<Search />
								<FollowPanel />
								<WhatsHappeningPanel />
								<Footer />
							</div>
						</aside>
					</div>
				</ThemeProvider>
			</body>
		</html>
	);
}
